version: '3.8'

services:
  rl-project:
    build: .
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:8080"  # For any web visualization
    command: python3 train_and_evaluate.py  # Default command, can be overridden

  # Service for running the trained model
  run-model:
    build: .
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python3 run_trained_model.py --model dqn  # Can be overridden with different model
